name: libero
args: []
kwargs: {}

dataset:
  _target_: "dataset_module.libero_dset.load_libero_slice_train_val"
  n_rollout: null
  # repo_id: "lerobot/libero_goal_image"
  # camera_key: "observation.images.image"
  # state_key: "observation.state"
  # action_key: "action"
  repo_id: "physical-intelligence/libero"
  camera_key: "image"
  state_key: "state"
  action_key: "actions"
  normalize_action: ${normalize_action}
  split_ratio: 0.9
  transform:
    _target_: "dataset_module.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 16