name: libero
args: []
kwargs: {}

dataset:
  _target_: "dataset_module.libero_dset.load_libero_slice_train_val"
  n_rollout: null
  normalize_action: ${normalize_action}
  split_ratio: 0.9
  transform:
    _target_: "dataset_module.img_transforms.default_transform"
    img_size: 224

decoder_path: null
num_workers: 16