name: pusht
args: []
kwargs: 
  with_velocity: true
  with_target: true

dataset:
  _target_: "dataset_module.pusht_dset.load_pusht_slice_train_val"
  with_velocity: true
  n_rollout: null
  normalize_action: ${normalize_action}
  data_path: ${oc.env:DATASET_DIR}/pusht_noise
  split_ratio: 0.9
  transform:
    _target_: "dataset_module.img_transforms.default_transform"
    img_size: ${img_size}
  use_precomputed_embeddings: ${model.use_precomputed_embeddings}
  embeddings_subdir: "dinov2_embeddings"
  use_waypoints: ${model.use_waypoint_mode}
  waypoints_subdir: "waypoints.pkl"
  waypoint_mode: "frameskip"  # "frameskip" or "waypoint_only"

decoder_path: null
num_workers: 16
prefetch_factor: 2